export const categories = [
  "B'Architect",
  "Computers & Servers",
  "Display Monitors",
  "Electronic Security",
  "Flash Memory & USB",
  "Hard Drives",
  "IP Surveillance",
  "KVM",
  "Memory Modules",
  "Miscellaneous",
  "Mobility",
  "Network Storage",
  "Networking",
  "Notebooks & Tablets",
  "Optical Drives",
  "Security",
  "Security Access Control",
  "Software",
  "Surveillance",
  "Telephony & UC",
  "UC Headset",
  "UPS",
  "Video & Audio Conferencing",
  "Warranty"
]